<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("B2B SHOP NEWS");
?><?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"ms_news", 
	array(
        "IBLOCK_TYPE" => COption::GetOptionString("kit.b2bshop", "NEWS_IBLOCK_TYPE", ""),
        "IBLOCK_ID" => COption::GetOptionString("kit.b2bshop", "NEWS_IBLOCK_ID", ""),
		"NEWS_COUNT" => "12",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"NUM_NEWS" => "20",
		"NUM_DAYS" => "180",
		"YANDEX" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_REVIEW" => "N",
		"USE_FILTER" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"CHECK_DATES" => "Y",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "#SITE_DIR#news/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_SHADOW" => "Y",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",
		"DISPLAY_PANEL" => "Y",
		"SET_TITLE" => "Y",
		"SET_STATUS_404" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"USE_PERMISSIONS" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "j F Y",
		"LIST_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "VIDEO",
			1 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"DISPLAY_NAME" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_ACTIVE_DATE_FORMAT" => "j F Y",
		"DETAIL_FIELD_CODE" => array(
			0 => "SHOW_COUNTER",
			1 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "FIRST",
			1 => "VIDEO",
		),
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "arrows",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "catalog",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
		"PAGER_SHOW_ALL" => "N",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"ADD_ELEMENT_CHAIN" => "Y",
		"FILTER_NAME" => "",
		"FILTER_FIELD_CODE" => array(
			0 => "MODIFIED_BY",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "FIRST",
			1 => "",
		),
		"COMPONENT_TEMPLATE" => "ms_news",
		"LIST_HEIGHT_IMG" => "220",
		"LIST_WIDTH_IMG" => "340",
		"DETAIL_HEIGHT_IMG" => "600",
		"DETAIL_WIDTH_IMG" => "820",
		"PAGER_MORE_NEWS" => "Y",
		"PAGER_MORE_NEWS_TEXT" => "Еще новости",
		"LIST_GO_DETAIL_PAGE" => "Подробнее",
		"DETAIL_BACK_LIST_TEXT" => "Вернуться к списку новостей",
		"POPULAR_TITLE" => "Популярное",
		"POPULAR_DISPLAY_DATE" => "Y",
		"POPULAR_DISPLAY_PICTURE" => "Y",
		"POPULAR_HEIGHT_IMG" => "400",
		"POPULAR_WIDTH_IMG" => "270",
		"POPULAR_DISPLAY_PREVIEW_TEXT" => "Y",
		"POPULAR_BACK_LIST_TEXT" => "Подробнее",
		"POPULAR_TRUNCATE_LEN" => "",
		"POPULAR_DISPLAY_SECTION" => "Y",
		"POPULAR_GO_DETAIL_PAGE" => "Подробнее",
		"POPULAR_NEWS_COUNT" => "3",
		"POPULAR_SORT_BY1" => "SHOW_COUNTER",
		"POPULAR_SORT_ORDER1" => "DESC",
		"POPULAR_SORT_BY2" => "ACTIVE_FROM",
		"POPULAR_SORT_ORDER2" => "DESC",
		"DISPLAY_PAGE_TITLE" => "1",
		"DISPLAY_PAGE_TITLE_SECOND" => "2",
		"DISPLAY_PAGE_TITLE_TEXT" => "",
		"DISPLAY_PAGE_TITLE_TEXT_SECOND" => "онлайн журнал",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "#SECTION_CODE#/",
			"detail" => "#SECTION_CODE#/#ELEMENT_CODE#/",
		)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>