<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Распродажа");
$APPLICATION->IncludeComponent(
	"bitrix:catalog",
	"ms_sales",
	Array(
		"ACTION_VARIABLE" => "action",
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_PICT_PROP" => "-",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "Y",
		"AJAX_OPTION_JUMP" => "Y",
		"AJAX_OPTION_STYLE" => "Y",
		"ALSO_BUY_ELEMENT_COUNT" => "3",
		"ALSO_BUY_MIN_BUYES" => "2",
		"AJAX_PRODUCT_LOAD" => COption::GetOptionString("kit.b2bshop","AJAX_PRODUCT_LOAD",""),
		"AVAILABLE_DELETE" => COption::GetOptionString("kit.b2bshop","AVAILABLE_DELETE","N"),
		"BASKET_URL" => COption::GetOptionString("kit.b2bshop","URL_CART",""),
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COLOR_IN_PRODUCT"=>COption::GetOptionString("kit.b2bshop", "COLOR_IN_PRODUCT", ""),
		"COLOR_IN_PRODUCT_CODE" => COption::GetOptionString("kit.b2bshop","COLOR_IN_PRODUCT_CODE",""),
		"COLOR_IN_PRODUCT_LINK"=>COption::GetOptionString("kit.b2bshop", "COLOR_IN_PRODUCT_LINK", ""),
		"COLOR_IN_SECTION_LINK"=>COption::GetOptionString("kit.b2bshop", "COLOR_IN_SECTION_LINK", "1"),
		"COLOR_IN_SECTION_LINK_MAIN"=>COption::GetOptionString("kit.b2bshop", "COLOR_IN_SECTION_LINK_MAIN", ""),
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "",
		"DELETE_OFFER_NOIMAGE" => COption::GetOptionString("kit.b2bshop","DELETE_OFFER_NOIMAGE",""),
		"DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
		"DETAIL_BRAND_USE" => "N",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
		"DETAIL_DETAIL_PICTURE_MODE" => "IMG",
		"DETAIL_DISPLAY_NAME" => "Y",
		"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
		"DETAIL_HEIGHT_BIG" => COption::GetOptionString("kit.b2bshop","DETAIL_HEIGHT_BIG",""),
		"DETAIL_HEIGHT_MEDIUM" => COption::GetOptionString("kit.b2bshop","DETAIL_HEIGHT_MEDIUM",""),
		"DETAIL_HEIGHT_SMALL" => COption::GetOptionString("kit.b2bshop","DETAIL_HEIGHT_SMALL",""),
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_OFFERS_FIELD_CODE" => array(0=>"NAME",1=>"",),
		"DETAIL_OFFERS_PROPERTY_CODE" => unserialize(COption::GetOptionString("kit.b2bshop","OFFER_TREE_PROPS","")),
		"DETAIL_PROPERTY_CODE" => unserialize(COption::GetOptionString("kit.b2bshop","ALL_PROPS","")),
		"DETAIL_SHOW_MAX_QUANTITY" => "N",
		"DETAIL_USE_COMMENTS" => "N",
		"DETAIL_USE_VOTE_RATING" => "N",
		"DETAIL_WIDTH_BIG" => COption::GetOptionString("kit.b2bshop","DETAIL_WIDTH_BIG",""),
		"DETAIL_WIDTH_MEDIUM" => COption::GetOptionString("kit.b2bshop","DETAIL_WIDTH_MEDIUM",""),
		"DETAIL_WIDTH_SMALL" => COption::GetOptionString("kit.b2bshop","DETAIL_WIDTH_SMALL",""),
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "Y",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "timestamp_x",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_FIELD_CODE" => array(0=>"",1=>"",),
		"FILTER_NAME" => "arrSalesFilter",
		"FILTER_OFFERS_FIELD_CODE" => array(0=>"PREVIEW_PICTURE",1=>"DETAIL_PICTURE",2=>"",),
		"FILTER_OFFERS_PROPERTY_CODE" => array(0=>"",1=>"",),
		"FILTER_PRICE_CODE" => unserialize(COption::GetOptionString("kit.b2bshop","PRICE_CODE","")),
		"FILTER_PROPERTY_CODE" => array(0=>"",1=>"",),
		"FILTER_VIEW_MODE" => "VERTICAL",
		"FLAG_PROPS" => unserialize(COption::GetOptionString("kit.b2bshop","FLAG_PROPS","")),
		"FORUM_ID" => "1",
		"HIDE_NOT_AVAILABLE" => COption::GetOptionString("kit.b2bshop","HIDE_NOT_AVAILABLE","L"),
		"IBLOCK_ID" => COption::GetOptionString("kit.b2bshop","IBLOCK_ID",""),
		"IBLOCK_TYPE" => COption::GetOptionString("kit.b2bshop","IBLOCK_TYPE",""),
		"IMAGE_RESIZE_MODE" => COption::GetOptionString( "kit.b2bshop", "IMAGE_RESIZE_MODE", "BX_RESIZE_IMAGE_PROPORTIONAL" ),
		"INCLUDE_SUBSECTIONS" => "Y",
		"IS_FANCY" => COption::GetOptionString("kit.b2bshop","IS_FANCY",""),
		"LABEL_PROP" => "-",
		"LAZY_LOAD"=>COption::GetOptionString( "kit.b2bshop", "LAZY_LOAD", "" ),
		"LINE_ELEMENT_COUNT" => "3",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"LINK_IBLOCK_ID" => "",
		"LINK_IBLOCK_TYPE" => "",
		"LINK_PROPERTY_SID" => "",
		"LIST_BROWSER_TITLE" => "NAME",
		"LIST_HEIGHT_MEDIUM" => COption::GetOptionString("kit.b2bshop","LIST_HEIGHT_MEDIUM",""),
		"LIST_HEIGHT_SMALL" => COption::GetOptionString("kit.b2bshop","LIST_HEIGHT_SMALL",""),
		"LIST_META_DESCRIPTION" => "-",
		"LIST_META_KEYWORDS" => "-",
		"LIST_OFFERS_FIELD_CODE" => array(0=>"NAME",1=>"PREVIEW_PICTURE",2=>"DETAIL_PICTURE",3=>"",),
		"LIST_OFFERS_LIMIT" => "0",
		"LIST_OFFERS_PROPERTY_CODE" => unserialize(COption::GetOptionString("kit.b2bshop","OFFER_TREE_PROPS","")),
		"LIST_PROPERTY_CODE" => array(0=>"",1=>"NEWPRODUCT",2=>"SALELEADER",3=>"SPECIALOFFER",4=>"",),
		"LIST_WIDTH_MEDIUM" => COption::GetOptionString("kit.b2bshop","LIST_WIDTH_MEDIUM",""),
		"LIST_WIDTH_SMALL" => COption::GetOptionString("kit.b2bshop","LIST_WIDTH_SMALL",""),
		"MAILING_EMAIL_SEND_END" => "<label>Вы подписаны на новинки категории</label>",
		"MAILING_INFO_TEXT" => "Хотите узнавать о новых поступлениях в данной категории?",
		"MAIN_TITLE" => "Наличие на складах",
		"MANUFACTURER_ELEMENT_PROPS" => COption::GetOptionString("kit.b2bshop","MANUFACTURER_ELEMENT_PROPS",""),
		"MANUFACTURER_LIST_PROPS" => COption::GetOptionString("kit.b2bshop","MANUFACTURER_LIST_PROPS",""),
		"MESSAGES_PER_PAGE" => "10",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_COMPARE" => "Сравнение",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"MORE_PHOTO_OFFER_PROPS" => COption::GetOptionString("kit.b2bshop","MORE_PHOTO_OFFER_PROPS",""),
		"MORE_PHOTO_PRODUCT_PROPS" => COption::GetOptionString("kit.b2bshop","MORE_PHOTO_PRODUCT_PROPS",""),
		"OFFERS_CART_PROPERTIES" => unserialize(COption::GetOptionString("kit.b2bshop","OFFER_TREE_PROPS","")),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_ORDER2" => "desc",
		"OFFER_ADD_PICT_PROP" => "-",
		"OFFER_COLOR_PROP" => COption::GetOptionString("kit.b2bshop","OFFER_COLOR_PROP",""),
		"OFFER_TREE_PROPS" => unserialize(COption::GetOptionString("kit.b2bshop","OFFER_TREE_PROPS","")),
		"PAGE_ELEMENT_COUNT_IN_ROW" => COption::GetOptionString( "kit.b2bshop", "CATALOG_LIST_COUNT_IN_ROW", "4" ),
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "catalog",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => COption::GetOptionString("kit.b2bshop","CATALOG_LIST_COUNT","36"),
		"PARTIAL_PRODUCT_PROPERTIES" => "Y",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"PICTURE_FROM_OFFER" => COption::GetOptionString("kit.b2bshop","PICTURE_FROM_OFFER",""),
		"PRELOADER"=>COption::GetOptionString( "kit.preloader", "IMAGE", "" ),
		"PRICE_CODE" => ($_SESSION["KIT_REGIONS"]["PRICE_CODE"] & COption::GetOptionString("kit.b2bshop","USE_MULTIREGIONS","Y") == 'Y')
			?$_SESSION["KIT_REGIONS"]["PRICE_CODE"]:unserialize(COption::GetOptionString("kit.b2bshop","PRICE_CODE","")),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_DISPLAY_MODE" => "N",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(0=>"CML2_MANUFACTURER",),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"REVIEW_AJAX_POST" => "Y",
		"SECTIONS_SHOW_PARENT_NAME" => "Y",
		"SECTIONS_VIEW_MODE" => "LIST",
		"SECTION_COUNT_ELEMENTS" => "N",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_TOP_DEPTH" => "1",
		"SEF_FOLDER" => "/catalog/",
		"SEF_MODE" => "Y",
		"SEF_URL_TEMPLATES" => array("sections"=>"","section"=>"/#SECTION_CODE#/","element"=>"/#SECTION_CODE#/#ELEMENT_CODE#/","compare"=>"compare/",),
		'SEOMETA_TAGS' =>  COption::GetOptionString("kit.b2bshop","SEOMETA_TAGS","BOTTOM"),
		"SET_STATUS_404" => "N",
		"SET_BROWSER_TITLE"=>"Y",
		"SET_META_KEYWORDS"=>"Y",
		"SET_META_DESCRIPTION"=>"Y",
		"SET_TITLE" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_LINK_TO_FORUM" => "Y",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_TOP_ELEMENTS" => "N",
		"STORE_PATH" => "/store/#store_id#",
		"TEMPLATE_THEME" => "blue",
		"URL_TEMPLATES_READ" => "",
		"USE_ALSO_BUY" => "Y",
		"USE_CAPTCHA" => "Y",
		"USE_COMPARE" => "N",
		"USE_ELEMENT_COUNTER" => "Y",
		"USE_FILTER" => "Y",
		"USE_MIN_AMOUNT" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "Y",
		"USE_REVIEW" => "Y",
		"USE_STORE" => "Y",
		"USE_STORE_PHONE" => "Y",
		"USE_STORE_SCHEDULE" => "Y",
	)
);
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>