<?php
IncludeModuleLangFile(__FILE__);
$sotbit_b2bshop_default_option = array(
    //style site
    'STYLE' => 'default',
    //main option
    'IBLOCK_TYPE' => 'b2bs_catalog',
    'MAIN_PROPS' => serialize(array(
        'SOSTAV',
        'CML2_ARTICLE',
        'RISUNOK_'
    )),
    'DOP_PROPS' => serialize(array(
        'SEZON',
        'STRANA_PROIZVODITEL',
        'CML2_MANUFACTURER',
        'POL',
        'VYREZ_GORLOVINY',
        'TIP_RUKAVA',
        'GABARITY_PREDMETOV',
        'DLINA_RUKAVA',
        'DEKORATIVNYE_ELEMENTY',
        'SHIRINA_RUKAVA',
        'POKROY',
        'STIL',
        'OSOBENNOSTI_TKANI',
        'VID_ZASTEZHKI',
        'FAKTURA_MATERIALA',
        'VOROTNIK',
        'TIP_KARMANOV',
        'KONSTRUKTIVNYE_ELEMENTY',
        'PO_NAZNACHENIYU',
        'MATERIAL_PODKLADKI',
        'RISUNOK_',
        'VYSOTA_KABLUKA',
        'VYSOTA_PLATFORMY',
        'MATERIAL_VERKHA',
        'MATERIAL_PODOSHVY',
        'FORMA_MYSKA',
        'FORMA_KABLUKA',
        'OSOBENNOST_MATERIALA_VERKHA',
        'MATERIAL_STELKI',
        'GOLENISHCHE',
        'FORMA_RUKAVA',
        'RUKAV',
        'VID_BRETELEK'
    )),  
    'FLAG_PROPS' => serialize(array(
        'SALE',
    )),            
    'PRICE_CODE' => serialize(array('BASE')),
    'OFFER_TREE_PROPS' => serialize(array('COLOR','RAZMER','OG','CHASHECHKI')),
    'OFFER_COLOR_PROP' => 'COLOR',
    'MANUFACTURER_ELEMENT_PROPS' => 'PROIZVODITEL_ATTR_E',
    'COUNT_BRAND_MENU' => '10',
    'MANUFACTURER_LIST_PROPS' => 'CML2_MANUFACTURER',
    'MORE_PHOTO_OFFER_PROPS' => 'MORE_PHOTO',
    'MORE_PHOTO_PRODUCT_PROPS' => 'MORE_PHOTO',
    'AVAILABLE_DELETE' => 'N',
    'PICTURE_FROM_OFFER' => 'Y',
    // list catalog
    'LIST_WIDTH_SMALL' => '70',
    'LIST_HEIGHT_SMALL' => '116',
    'LIST_WIDTH_MEDIUM' => '255',
    'LIST_HEIGHT_MEDIUM' => '425',
    'FILTER_ITEM_COUNT' => '8', 
    'CATALOG_LIST_COUNT' => '24',  
    // detail catalog
    'DETAIL_WIDTH_SMALL' => '52',
    'DETAIL_HEIGHT_SMALL' => '87',
    'DETAIL_WIDTH_MEDIUM' => '373',
    'DETAIL_HEIGHT_MEDIUM' => '623',
    'DETAIL_WIDTH_BIG' => '5000',
    'DETAIL_HEIGHT_BIG' => '5000',
    'DOWNLOAD' => 'Y',
    'IS_FANCY' => 'N',
    'COLOR_FROM_IMAGE' => 'N',
    'COLOR_IMAGE_WIDTH' => '37',
    'COLOR_IMAGE_HEIGHT' => '100',
    'DETAIL_TEXT_INCLUDE' => GetMessage('DETAIL_TEXT_INCLUDE_DEFAULT'),
    // basket and order
    'URL_CART' => '/personal/cart/',
    'URL_ORDER' => '/personal/order/make/',
    'URL_PERSONAL' => '/personal/',
    'URL_PAYMENT' => '/personal/order/payment/',
    'URL_PAGE_ORDER' => '/personal/order/',
    'CART_IMG_WIDTH' => '170',
    'CART_IMG_HEIGHT' => '200',
    'CART_IN_ORDER' => 'Y',
    //table size
    'TABLE_SIZE_URL' => '/clients/table_sizes/#table', 
    'SIZE_PROPS' => serialize(array('RAZMER','CHASHECHKI')),  
    // zone site
    'LOGO' => '/bitrix/templates/b2b_shop/img/b2b_header_logo.png',
    'TEL' => GetMessage('TEL_DEFAULT'),
    'COPYRIGHT' => GetMessage('COPYRIGHT_DEFAULT'),
    // social link
    'LINK_VK' => 'https://vk.com/sotbit',
    'LINK_FB' => 'https://www.facebook.com/sotbit',
    'LINK_TW' => 'https://twitter.com/sotbit',
    //yndex and google
    'YANDEX' => GetMessage('YANDEX'),  
    'GOOGLE' => GetMessage('GOOGLE'),  
    //microrazmetka
    'MICRO_ORGANIZATION_NAME' => 'B2B shop',
    'MICRO_ORGANIZATION_TYPE1' => 'Organization',
    'MICRO_ORGANIZATION_TYPE2' => 'LocalBusiness', 
    'MICRO_ORGANIZATION_TYPE3' => 'Store', 
    'MICRO_ORGANIZATION_PHONE' => serialize(array('8 800 111 11 11')), 
    'MICRO_ORGANIZATION_STRANA' => 'Russia',        
    'MICRO_ORGANIZATION_LOGO' => '/bitrix/templates/b2b_shop/img/b2b_header_logo.png',
    'MICRO_ORGANIZATION_LOGO_NAME' => 'B2B shop',
    'MICRO_ORGANIZATION_LOGO_WIDTH' => '534',
    'MICRO_ORGANIZATION_LOGO_HEIGHT' => '208',
    'MICRO_TOVAR_NAME' => '#NAME#',
    'MICRO_TOVAR_DESCRIPTION' => '#IPROPERTY_VALUES||ELEMENT_META_DESCRIPTION#',
    'MICRO_TOVAR_PRICE' => '#PROPERTIES||MAXIMUM_PRICE||VALUE#',
    'MICRO_TOVAR_PRICE_CURRENCY' => '#MIN_PRICE||CURRENCY#',
    'MICRO_TOVAR_ITEM_AVAILABILITY_TRUE' => 'InStock',
    'MICRO_TOVAR_ITEM_AVAILABILITY_FALSE' => 'OutOfStock',
    'MICRO_TOVAR_ITEM_CONDITION' => 'NewCondition',
    'MICRO_TOVAR_PAYMENT_METHOD' => serialize(array('VISA','MasterCard','Cash','COD')), 
    'MICRO_ARTICLE_NAME' => '#NAME#',
    'MICRO_ARTICLE_DESCRIPTION' => '#PREVIEW_TEXT#',
    'MICRO_ARTICLE_TYPE' => 'NewsArticle',
    'MICRO_ARTICLE_KEYWORDS' => '#IPROPERTY_VALUES||ELEMENT_META_KEYWORDS#',
    'MICRO_ARTICLE_LANGUAGE'  => 'ru',
    'MICRO_ARTICLE_IMAGE' => '#DETAIL_PICTURE||RESIZE||SRC#',
    'MICRO_ARTICLE_AUTHOR' => 'Organization'    
);